// CWE416 Use After Free 测试函数声明
// 自动生成，仅包含有实现的测试用例

#ifndef CWE416_DECLARATIONS_H
#define CWE416_DECLARATIONS_H

// char类型测试函数
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_02_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_03_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_04_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_05_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_06_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_07_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_08_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_09_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_10_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_11_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_12_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_13_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_14_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_15_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_16_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_17_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_char_18_bad(void);

// int64_t类型测试函数
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_02_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_03_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_04_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_05_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_06_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_07_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_08_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_09_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_10_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_11_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_12_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_13_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_14_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_15_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_16_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_17_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_int64_t_18_bad(void);

// long类型测试函数
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_02_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_03_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_04_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_05_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_06_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_07_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_08_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_09_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_10_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_11_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_12_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_13_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_14_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_15_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_16_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_17_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_long_18_bad(void);

// struct类型测试函数
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_02_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_03_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_04_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_05_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_06_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_07_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_08_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_09_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_10_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_11_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_12_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_13_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_14_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_15_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_16_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_17_bad(void);
extern void CWE416_Use_After_Free__kfence_alloc_kfence_free_struct_18_bad(void);

// return_freed_ptr类型测试函数
extern void CWE416_Use_After_Free__return_freed_ptr_02_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_03_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_04_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_05_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_06_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_07_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_08_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_09_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_10_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_11_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_12_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_13_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_14_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_15_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_16_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_17_bad(void);
extern void CWE416_Use_After_Free__return_freed_ptr_18_bad(void);

#endif // CWE416_DECLARATIONS_H 